apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-clusterip
  labels: 
    app : backend
spec:
   template: 
      metadata: 
       name : myapp-pod
       labels: 
         app : nginxclusterip
      spec:
        containers:
           - name : nginximage
             image: nginx   
   selector:
     matchLabels:
        app: nginxclusterip
   replicas : 2     
