apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels: 
    app : backend
spec:
   template: 
      metadata: 
       name : myapp-pod
       labels: 
         app : backend
      spec:
        containers:
           - name : nginximage
             image: nginx   
   selector:
     matchLabels:
        app: backend
   replicas : 3          